
---
title:           Lockdown Greenspace Access
author:          Dr Ali Lakhani, Dr Dennis Wollersheim, Mr Prosper Korah, Professor Elizabeth Kendall
date:            25.07.2020
linkcolor:       cyan
citecolor:       grey
output:
workflowr::wflow_html:
code_folding: hide
---

\tableofcontents


```{r init, include=F}

source('_drake.R')

loadd(df_mesh_lockdown_summary_residential)
loadd(df_mesh_lockdown_summary_parks)
loadd(df_mesh_lockdown_summary_all)
loadd(map_mesh)
loadd(map_sa1)
loadd(map_sa2)
loadd(map_lockdown_lga)
loadd(df_mesh_lockdown)
loadd(df_mesh_detail)
loadd(max_distance)
```

# No Parkland Meshblock Summary


```{r none}

  df_mesh_lockdown_summary_all %>%
    filter(as.numeric(area)==0) %>%
  { . } -> df_none

df_none %>%
  count( MB_CATEGORY_NAME_2016, sort=TRUE) %>%
  gt::gt() %>%
  gt::tab_header(
           title = glue::glue("Meshblocks with no parks within {max_distance}km"),
           subtitle = "Number by category"
)

df_none %>%
  select(-starts_with('mc'), -State) %>%
  summarise( across( where(is.numeric),
                    .fns=list(mean=mean, max=max, min=min, sd=sd, total = sum))) %>%
  gt::gt() %>%
gt::tab_header(
               title = glue::glue("Meshblocks with no parks within {max_distance}km"),
               subtitle = "Summary statistics"
)
```

# LGA level summary for Residential Meshblocks


```{r lga}

df_mesh_lockdown_summary_residential  %>%
  group_by(lga_name) %>%
  select(-starts_with('mc'), -State) %>%
  mutate( area = units::set_units( area, 'km^2') ) %>%
  summarise(across(.cols=where(is_numeric),
                   .fns=list(mean=mean, max=max, min=min, sd=sd, total = sum),
                   .names = "{col}.{fn}"), number_mesh_blocks = n(),
            .groups='drop') %>%
  { . } -> df_lga_summary

df_lga_summary %>%
  datatable(options = list(pageLength = 10))

df_mesh_lockdown_summary_all  %>%
  write_csv('output/lockdown_greenspace_mesh_detail.csv')

df_lga_summary %>%
  write_csv('output/lockdown_greenspace_lga_summary.csv')

```

# SA2 level summary for Residential Meshblocks

```{r SA2}

df_mesh_lockdown_summary_residential  %>%
  select(-starts_with('mc'), -State) %>%
  mutate( area = units::set_units( area, 'km^2') ) %>%
  group_by(SA2_MAIN16) %>%
  summarise(across(.cols=where(is_numeric),
                   .fns=list(mean=mean, max=max, min=min, sd=sd, total = sum),
                   .names = "{col}.{fn}"), number_mesh_blocks = n(),
            .groups='drop') %>%
  right_join( df_mesh_lockdown_summary_all %>% distinct(SA2_MAIN16), by ='SA2_MAIN16' ) %>%
  { . } -> df_sa2_summary

df_sa2_summary %>%
  head(10) %>%
  gt::gt() %>%
gt::tab_header(
               title = "SA2 Summary",
               subtitle = "First 10 rows"
)

df_sa2_summary %>%
  write_csv('output/lockdown_greenspace_sa2_summary.csv')

```

# SA1 level summary

```{r SA1}

df_mesh_lockdown_summary_residential  %>%
  select(-starts_with('mc'), -State) %>%
  mutate( area = units::set_units( area, 'km^2') ) %>%
  group_by(SA1_MAIN16) %>%
  summarise(across(.cols=where(is_numeric),
                   .fns=list(mean=mean, max=max, min=min, sd=sd, total = sum),
                   .names = "{col}.{fn}"), number_mesh_blocks = n(),
            .groups='drop') %>%
  right_join( df_mesh_lockdown_summary_all %>% distinct(SA1_MAIN16), by ='SA1_MAIN16' ) %>%
  { . } -> df_sa1_summary

df_sa1_summary %>%
  head(10) %>%
  gt::gt() %>%
  gt::tab_header(
                 title = "SA1 Summary",
                 subtitle = "First 10 rows"
  )


df_sa1_summary %>%
  write_csv('output/lockdown_greenspace_sa1_summary.csv')

```

# Map
```{r map1}

map_sa1 %>%
  inner_join(df_sa1_summary, by = "SA1_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  ggplot() +
  geom_sf( aes( fill = area.mean ),lwd=0 ) +
  scale_fill_viridis_c(option = "plasma") +
  ggtitle(glue::glue('Km^2 greenspace access within {max_distance}km of meshblock average for SA1'))


map_sa2 %>%
  inner_join(df_sa2_summary, by = "SA2_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  ggplot() +
  geom_sf( aes( fill = area.mean ),lwd=0 ) +
  scale_fill_viridis_c(option = "plasma") +
  ggtitle(glue::glue('Km^2 greenspace access within {max_distance}km of meshblock average for SA2'))

```

# Green Map
```{r map2}

map_mesh %>%
  inner_join(df_mesh_lockdown_summary_parks, by = "MB_CODE16" ) %>%
  { . } -> df_parks

map_sa1 %>%
  inner_join(df_sa1_summary, by = "SA1_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  ggplot() +
  geom_sf( aes( fill = area.mean ),lwd=0 ) +
  geom_sf(data=df_parks, fill=RColorBrewer::brewer.pal(3,'Greens')[2]) +
  scale_fill_viridis_c(option = "plasma") +
  ggtitle(glue::glue('Km^2 greenspace access within {max_distance}km of meshblock. Green is parks'))

map_sa2 %>%
  inner_join(df_sa2_summary, by = "SA2_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  ggplot() +
  geom_sf( aes( fill = area.mean ),lwd=0 ) +
  geom_sf(data=df_parks, fill=RColorBrewer::brewer.pal(3,'Greens')[2]) +
  scale_fill_viridis_c(option = "plasma") +
  ggtitle(glue::glue('Km^2 greenspace access within {max_distance}km of meshblock. Green is parks'))


```


# Interactive Map SA2 level
```{r interactive_map2}

map_breaks = 0:5/5 * max_distance^2
map_levels = paste0( map_breaks, '-', map_breaks + map_breaks[2] - map_breaks[1], 'km' )
map_levels [[length(map_levels)-1]] = paste0('>', map_breaks[[ length(map_breaks)-1]], 'km' )
map_levels = map_levels [1:length(map_levels)-1] 
map_breaks[[length(map_breaks)]] = 3.2*max_distance^2


#map_levels = c('0-5km^2', '5-10km^2', '10-15km^2','15-20km^2','>20km^2')
map_colors = RColorBrewer::brewer.pal(6,'YlOrRd')[2:6]
map_palette = colorFactor(map_colors, levels=map_levels)

map_sa2 %>%
  inner_join(df_sa2_summary, by = "SA2_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  mutate( area_factor = cut( area.mean, breaks=map_breaks,
                            labels= map_levels )) %>%
  { . } -> df_leaflet


df_leaflet %>%
  leaflet() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~map_palette(area_factor)) %>%
  addLegend("bottomright", pal = map_palette, values = ~area_factor,
            title = "Mean park area within 5km circle of mesh blocks within SA2",
            opacity = 1
            ) %>%
  addPolygons( weight = .5, smoothFactor = 0.5,
              opacity = .5, fillOpacity = 0.0,
              data = map_lockdown_lga) %>%
  addPolygons( weight = 1, smoothFactor = 0.5,
              opacity = 1, fillOpacity = 1,
              color = RColorBrewer::brewer.pal(3,'Greens')[2],
              data = df_parks)

```

# Interactive Map SA1 level
```{r interactive_map1}

map_levels = c('0-5km^2', '5-10km^2', '10-15km^2','15-20km^2','>20km^2')
map_colors = RColorBrewer::brewer.pal(6,'YlOrRd')[2:6]
map_palette = colorFactor(map_colors, levels=map_levels)

map_sa1 %>%
  inner_join(df_sa1_summary, by = "SA1_MAIN16" ) %>%
  mutate( area.mean = area.mean %>% as.numeric() ) %>%
  mutate( area_factor = cut( area.mean, breaks=map_breaks,
                            labels= map_levels )) %>%
  { . } -> df_leaflet


df_leaflet %>%
  leaflet() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~map_palette(area_factor)) %>%
  addLegend("bottomright", pal = map_palette, values = ~area_factor,
            title = "Mean park area within 5km circle of mesh blocks within SA2",
            opacity = 1
  ) %>%
  addPolygons( weight = .5, smoothFactor = 0.5,
              opacity = .5, fillOpacity = 0.0,
              data = map_lockdown_lga) %>%
  addPolygons( weight = 1, smoothFactor = 0.5,
              opacity = 1, fillOpacity = 1,
              color = RColorBrewer::brewer.pal(3,'Greens')[2],
              data = df_parks)

```
